export default {
  MAIN_ROUTE: 'MAIN_ROUTE',
  AUTHSCREEN: 'AUTHSCREEN',
  HOMENAVIGATOR: 'HOMENAVIGATOR',
  HOMESCREEN: 'HOMESCREEN',
  EVENTDETAILSSCREEN: 'EVENTDETAILSSCREEN',
  PROFILESCREEN: 'PROFILESCREEN',
  FAVORITESCREEN: 'FAVORITESCREEN',
};
