export default {
  MAIN_ROUTE: 'MAIN_ROUTE',
  ONBOARDING: 'ONBOARDING',
  HOMESCREEN: 'HOMESCREEN',
  EVENTDETAILSSCREEN: 'EVENTDETAILSSCREEN',
  PROFILESCREEN: 'PROFILESCREEN',
  LOGINSCREEN: 'LOGINSCREEN',
  SIGNUPSCREEN: 'SIGNUPSCREEN',
};
